pipeline {
    agent any

    environment {
        IMAGE_NAME = "chinmaich316/redis-chat-app"
        DOCKER_CRED = "docker-cred"

        AWS_ACCESS_KEY = credentials('aws-access-key')
        AWS_SECRET_KEY = credentials('aws-secret-key')
    }

    stages {

        stage('Checkout Code') {
            steps {
                
                echo '✅ Code checked out from GitHub'
                
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                dir('redis-chat-app') {
                    sh "docker build -t ${IMAGE_NAME}:latest ."

                    withCredentials([usernamePassword(credentialsId: "${DOCKER_CRED}", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh "echo $PASS | docker login -u $USER --password-stdin"
                        sh "docker push ${IMAGE_NAME}:latest"
                    }

                    echo '✅ Docker image built & pushed successfully'
                }
            }
        }

        stage('Terraform Init') {
            steps {
                dir('redis-chat-app/Terraform') {
                    sh """
                        export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
                        export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
                        terraform init
                    """
                }
                echo '✅ Terraform initialized successfully'
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('redis-chat-app/Terraform') {
                    sh """
                        export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
                        export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
                        terraform apply -auto-approve
                    """
                }
                echo '✅ EC2 instance created successfully'
            }
        }

        stage('Deploy') {
            steps {
                script {

                    def PUBLIC_IP = sh(
                        script: "cd redis-chat-app/Terraform && terraform output -raw instance_public_ip",
                        returnStdout: true
                    ).trim()

                    PUBLIC_IP = PUBLIC_IP.replaceAll('[^0-9\\.]', '')

                    echo "🔗 Connecting to EC2 instance at: ${PUBLIC_IP}"

                    sshagent(['ec2-ssh-key']) {
                        sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} '
                    echo " Pulling Docker image..."
                    docker pull ${IMAGE_NAME}:latest
                    # create network if it doesn't exist
                    docker network create chat-network || true
                    # stopping and remove old containers if present
                    docker stop redis-chat-app || true
                    docker rm redis-chat-app || true
                    # starting redis on chat-network
                    docker run -d --name redis --network chat-network redis:latest
                    # start app on chat-network and map ports
                    docker run -d -p 5000:8080 --name redis-chat-app --network chat-network -e REDIS_HOST=redis -e REDIS_PORT=6379 ${IMAGE_NAME}:latest
                    '
                    """
                    }

                    echo '🚀 Application deployed successfully to EC2'
                }
            }
        }
    }

    post {
        success {
            echo '🎉 CI/CD pipeline completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed! Check logs.'
        }
    }
}

